- contribute.md
> gds-725: Added conttribution MD

- config.json
- dist/index.html
- gulpfile.js
- added sorting function to order pages generated by metalsmith
- edited config to allow the use of additional configurations during build
> GDS-752 - sort order for metalsmith

- src/components/card/_card.scss
- src/components/direction-links/_direction-links.scss
- src/components/pagination/_pagination.scss
- src/components/site-wide-message/_site-wide-message.scss
- src/global/scss/settings/_settings.scss
- src/global/scss/tools/_focus.scss
- src/global/scss/tools/_links.scss
- src/patterns/footer/_footer.scss
- src/patterns/header/_header.scss
- src/styles/forms/_forms.scss
- src/styles/typography/_typography.scss
- added new color for focus state to `settings.scss`
- updated focus mixin to include some new arguements include `$offset` and `$color`
- updated where needed the color or offset depending on the focus usage
- created custom focus for radio buttons
> GDS-744 - focus-state

- src/components/card/_card.scss
- src/components/card/index.hbs
- src/global/scss/style/_grid.scss
- src/global/scss/tools/_grid.scss
- src/styles/grid/_grid.hbs
- removed height from grid column styles
- added example of multiple cards in a grid
> GDS-754 - fix for card alignment

- src/global/scss/settings/_settings.scss
- src/styles/typography/_typography.hbs
- src/styles/typography/_typography.scss
- changed font size mapping, mobile from lg to xxxl, changed the xxxl desktop size
- removed the styles for paragraphs followed by any element
- changed h3, h4, h5, h6 styles
- added style for h3 following a h2, h4 following a h3, h5 following a h4
> GDS-761 - heading sizes and spacing update

- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/card/_card.scss
- src/patterns/footer/_footer.scss
- tightened up spacing in footer between links to make groups appear consistent
- removed visited styling from footer links and cards
- changed font for breadcrumbs from bold to regular, added correct colors for links
> feat: small visual updates to clean up design based on feedback

- src/components/in-page-navigation/_in-page-navigation.scss
- src/global/scss/tools/_links.scss
- updated font size for the title from small to medium based of design feedback
- updated focus for "text-links" to have an offset
> fix: heading size for in-page nav and focus state 

- src/components/tab-navigation/_tab-navigation.scss
- changed selected state color to `nsw-primary-highlight`
- updated unselected text color to `nsw-primary-blue`
- added color to selected text
> feat: updated tab navigation as per design change

- src/components/hero-search/_hero-search.hbs
- src/components/hero-search/_hero-search.scss
- src/components/hero-search/hero-search.json
- src/components/hero-search/index.hbs
- src/global/scss/tools/_focus.scss
- src/main.scss
- src/styles/forms/_forms.scss
- src/styles/typography/_typography.scss
- created html, css and json for the hero search component
- updated focus mixin to account for browser styling for offset on inputs
- added new class `.nsw-body-content` for body content styles in other components to be a bit more DRY
- added a search input style to the forms.scss
> feat: added new component hero search and small changes

- src/styles/typography/_typography.hbs
- src/styles/typography/_typography.scss
also included are abbr and acronym
> feat: styled remaining typography element ul, ol, dl and small

- src/components/feature-tile/_feature-tile-title.hbs
- src/components/feature-tile/_feature-tile.hbs
- src/components/feature-tile/_feature-tile.scss
- src/components/feature-tile/feature-tile-cta.json
- src/components/feature-tile/feature-tile-five-links.json
- src/components/feature-tile/feature-tile-links.json
- src/components/feature-tile/feature-tile.json
- src/components/feature-tile/index.hbs
- src/global/handlebars/layouts/layout.hbs
- src/global/scss/style/_base.scss
- src/main.scss
- src/styles/grid/_grid.hbs
- src/styles/grid/index.hbs
- src/templates/full-width-test/index.hbs
- src/templates/nav-sidebar-left/index.hbs
- src/templates/sidebar-left/index.hbs
- src/templates/sidebar-right/index.hbs
- also adjusted styles for example grid and template pages to make it easier for content editors on design system site
- reordered sass imports to allow typography style to be overwritten by components
> feat: added new feature tile component

- src/global/scss/style/_base.scss
- src/patterns/header/_header.hbs
- src/templates/full-width-hero-banner/index.hbs
- src/templates/full-width-hero-search/index.hbs
- src/templates/full-width/index.hbs
- src/templates/nav-sidebar-left/index.hbs
- src/templates/nav-sidebar-right/index.hbs
- src/templates/sidebar-left/index.hbs
- src/templates/sidebar-right/index.hbs
- added hero-search and hero-banner templates
- cleaned up template code
- fixed broken html in header
- renamed full-width template folder
> feat: cleaned up and added more templates

- .github/workflows/build-deploy-staging.yml
- .pa11yci
- src/components/hero-search/_hero-search.hbs
- src/components/in-page-navigation/_in-page-navigation.hbs
- src/patterns/header/_header.hbs
- src/patterns/header/_header.scss
- src/styles/iconography/_iconography.hbs
- src/styles/tables/_tables.hbs
- src/styles/tables/index.hbs
- src/styles/typography/_typography.hbs
- src/templates/full-width-hero-banner/index.hbs
- src/templates/full-width-hero-search/index.hbs
- src/templates/nav-sidebar-left/index.hbs
- src/templates/sidebar-right/index.hbs
added accessibiltiy test in the pipeline and also adressed accessibility complaints.
One particular change was to add the header and hero banner search form a button with submit type for non-keyboard users.
> ci: add pa11y tests

- src/components/feature-tile/index.hbs
> Change less to fewer

- src/components/button/_button.scss
- src/components/notification/_notification.scss
- src/components/site-wide-message/_site-wide-message.scss
https://stackoverflow.com/questions/57455245/how-to-i-solve-this-sass-interpolation-issue
> fix: sass interpolation issue

- gulpfile.js
- src/docs/docs.scss
- src/global/handlebars/layouts/partials/_docs-header.hbs
Design for review by @amy-howard -
> Fixes #195 - Add version number to docs

- gulpfile.js
- package-lock.json
- package.json
Updated rollup
Removed rollup-plugin-babel
Installed @rollup/plugin-babel
> Updated rollup dependency

- .github/workflows/build-deploy-production-manual.yml
- .github/workflows/build-deploy-production.yml
- .github/workflows/build-deploy-staging.yml
- .github/workflows/build-deploy-surge-backup.yml
- .github/workflows/publish-package.yml
Reverts digitalnsw/nsw-design-system#356
> Revert "Bump actions/setup-node from 3 to 4"

- .github/workflows/build-deploy-production-manual.yml
- .github/workflows/build-deploy-production.yml
Reverts digitalnsw/nsw-design-system#370
> Revert "Bump JamesIves/github-pages-deploy-action from 4.4.3 to 4.5.0"

- src/docs/docs.js
> Adds link sanitisation for all navLinks making solution environment agnostic

- vercel.json
This pull request introduces a `vercel.json` configuration file to manage deployment settings for our project on Vercel. The primary motivation behind this change is to explicitly disable automatic deployments to the `gh-pages` branch, ensuring that our deployment process is streamlined and aligns with our project's workflow.
By configuring Vercel in this way, we can prevent unwanted deployments to `gh-pages`, which may lead to inconsistencies or conflicts with our main branch workflow. This addition enhances our deployment strategy, providing greater control over how and when our application is deployed.
Overall, this change improves the project by establishing a clearer deployment configuration, which will help maintain the integrity of our deployment process moving forward.
> chore(vercel.json): add deployment configuration file

- src/core/colour/json/palettes.json
- src/docs/content/design/theming.hbs
- src/docs/docs.scss
- src/global/handlebars/helpers/getTextColor.js
This pull request introduces significant enhancements to the color definitions and theming capabilities of our project. By refining the color palette, implementing a dynamic theming grid, and adding a helper function to calculate text color based on background color, we aim to improve the visual consistency and accessibility of our user interface.
1. **Color Palette Updates**: 
- Removed redundant colors and introduced a more streamlined palette in `palettes.json`, ensuring a focused selection of colors that better represent our design principles.
- Added neutral colors (black, white, off-white) to enhance contrast and readability.
2. **Dynamic Theming Grid**:
- Implemented a responsive grid layout in the documentation to visually showcase the color palettes. This dynamic grid adjusts …
> feat(colour, docs, helpers): Enhance color definitions, implement dynamic theming grid, and add getTextColor helper

- src/global/scss/settings/_aboriginal-palette.scss
Updates the yellow and grey palette colors in our SCSS settings file to improve the visual consistency and aesthetics of our project. The adjustments to the yellow palette enhance the vibrancy and warmth of the colors, making them more appealing and effective for user interfaces. 
Additionally, comments have been clarified for better readability and maintainability, ensuring that future developers can easily understand the purpose of each color in the palette. 
By refining these color definitions, we aim to create a more cohesive design language across our application, ultimately leading to an improved user experience.
> style(scss): update yellow and grey palette colors and adjust comments for clarity

- .github/workflows/openai-pr-description.yml
- src/components/tabs/_tabs.scss
Introduces two significant updates to our project: an enhancement to the PR description action and improvements to the focus outline in the tabs component.
1. **Update PR Description Action**: 
- We are replacing the existing OpenAI PR description action with a more up-to-date version from the `digitalnsw` repository. This change ensures that we benefit from any improvements, bug fixes, and new features that have been implemented since the last version we were using. Keeping our tools current is crucial for maintaining efficiency and effectiveness in our development workflow.
2. **Enhance Focus Outline**: 
- The modifications to the `_tabs.scss` file enhance the accessibility of our tabs component. By improving the focus outline, we ensure that users navigating via keyboard can clearly …
> chore(workflows): Update PR description action and style(tabs.scss): Enhance focus outline

- src/docs/content/about/whats-happening.hbs
Adds comprehensive release notes for version 3.22.2 to the `whats-happening.hbs` documentation file. 
Keeping our documentation up-to-date with accurate release notes is essential for informing users about new features, improvements, and changes. This update highlights key patches introduced in version 3.22.2, specifically the addition of new border variant styles for the card component and new templates for showcasing these styles.
By adding these release notes, we enhance our project's transparency and usability, allowing developers to easily understand the latest updates and effectively implement new features. This change will facilitate better adoption of the design system and contribute to a smoother development experience.
> docs(whats-happening.hbs): add release notes for version 3.22.2

- add-component.js
- src/components/card-carousel/swipe-content.js
- src/components/cookie-consent/cookie-consent.js
- src/components/filters/filters.js
- src/components/tooltip/tooltip.js
- src/components/utility-list/utility-list.js
- src/global/handlebars/helpers/debug.js
- src/global/scripts/helpers/logger.js
This pull request aims to centralize the logging mechanism across the project. By introducing a dedicated logging helper, we improve consistency in how logs are handled, making the codebase cleaner and easier to maintain. This approach also allows us to easily toggle logging behavior based on the environment, ensuring that logs are only displayed during development and not in production.
1. **Introduced a Logging Helper**: A new module `logger.js` has been created to encapsulate the logging functionality. This module checks the `NODE_ENV` environment variable to determine whether to display logs.
2. **Updated Logging Calls**: All instances of console logging across various files have been replaced with calls to the new logging helper. This includes:
- File creation feedback in …
> refactor: centralize runtime logging

- src/components/filters/filters.js
Addresses an issue with the aggregation of selected values in the multi-select feature of the Filters component. The previous implementation was inefficient and could lead to unexpected behavior when handling multiple selections.
Key changes include:
- The refactoring of the `getMultiSelectValues` method to use the `push` method along with the spread operator. This ensures that all selected options from the multi-select elements are aggregated correctly into a single array.
By improving the logic for gathering selected options, this change enhances the reliability of the Filters component, ensuring that it accurately reflects user selections. This will lead to a better user experience and more consistent behavior in our application.
> Fix multi-select value aggregation in Filters component

- src/components/breadcrumbs/_breadcrumbs.scss
- src/docs/content/about/whats-happening.hbs
- src/docs/expandable-search.js
This pull request introduces several enhancements to the breadcrumbs and expandable search functionalities, addressing both styling and usability issues.
1. **Breadcrumbs Styling Improvement**: The breadcrumbs component now explicitly sets `text-decoration: none;` to ensure consistency in link appearance. This adjustment enhances the visual clarity and user interaction, preventing any default link styles from causing confusion.
2. **Expandable Search Usability Enhancements**: 
- Improved keyboard navigation by allowing users to submit their search selection using the Enter key. This feature enhances accessibility and provides a more intuitive experience for keyboard users.
- The code now correctly handles both mouse clicks and keyboard events, ensuring that users can easily navigate to …
> Breadcrumbs and expandable search fixes

- src/docs/content/about/whats-happening.hbs
Updates the release notes for the project to reflect the latest changes and improvements made in version 3.22.5. 
Keeping the release notes current is crucial for transparency and effective communication with our users. By updating the notes, we ensure that users are informed about the latest patches, improvements, and their corresponding pull requests. This not only enhances user experience but also encourages contributions and engagement within the community.
- The version number has been updated to v3.22.5, along with the corresponding release date.
- Added detailed descriptions of the patches included in this release, ensuring users have clear insights into what has been fixed or enhanced.
- Maintained a clear structure for ease of reading, which helps users quickly find relevant …
> Updates Release notes

- src/docs/content/about/whats-happening.hbs
Updates the "What's Happening" section of our documentation to reflect the recent changes introduced in version 3.22.7. 
The motivation behind this update is to ensure that our users are informed about the latest enhancements and fixes, particularly regarding accessibility improvements made to our Design System. By adding details about the new Axe-core accessibility testing workflow and the adjustments made to various components, we aim to highlight our commitment to meeting WCAG criteria and improving user experience.
This change enhances our documentation by providing clear and concise information about the updates, fostering transparency and keeping our community engaged with the ongoing development of the project.
> Updates what's happening
